# See: https://www.checkov.io/1.Welcome/Quick%20Start.html

compact: true
quiet: true
skip-path:
  - coverage
  - node_modules
skip-check:
  - CKV2_GHA_1 # Skip "write-all" check - we use job-level permissions, not top-level
